### ISSUE TITLE
Calculate origo

### ISSUE THREAD

**Issue by Daniel-Keri** [k0zyrev/dsoAhkQoL#1]
Hey man, can you hit me up on discord for a very quick talk?
adrenal_in

**Comment by k0zyrev** [comment]
Hi. Sry for late response. Why don't you just ask whatever you wanted to ask here?

**Comment by Daniel-Keri** [comment]
I wanted to extend the script you priveded (very good work tho!)
The idea was to understand how can i calculate the positions in the inventory (or basically anywhere)
I read the description obviously, but I couldn't make it. 

_Reason I asked if you have time on discord, is because it's not related to code, but it is to my english I didnt catch_

**Comment by k0zyrev** [comment]
https://i.imgur.com/cPfTw2U.jpg

Hope it helps, I tried to illustrate how it works in case of the element on the left side of the screen. Other cases explained in text and should be self-evident once you figure out this one. And really, you only need this if you play in window and window's resolution changes from time to time. If you always play in fullscreen at constant resolution, you can just hardcode coordinates of whatever UI element you need. If you play windowed, you also need to add offsets to take window borders into account.

ps I took a random screenshot from steam forums because I don't have the game installed. It's not mine.

**Comment by Daniel-Keri** [comment]
thank you very much, one more question that should be in a different "issue" don't you know that is it possible to simulate clicks on every drakensang client or window issued by a name? this works with setting a name but it's possible to send keys from A client to x,y,z?

**Comment by k0zyrev** [comment]
That is out of the scope of this script and my knowledge of autohotkey. You should be able to get a much better help by asking in autohokey communities, for example on reddit https://old.reddit.com/r/AutoHotkey/

**Comment by Daniel-Keri** [comment]
Thanks for your help very much. Good work!
